
# Questão 01
CREATE TABLE PRODUTO(
ID INT NOT NULL AUTO_INCREMENT , 
NOME VARCHAR(50) NOT NULL, DESCRICAO VARCHAR(120) NOT NULL, 
DESCONTO FLOAT(10,2) NOT NULL, 
DATA DATE NOT NULL, 
PRIMARY KEY(ID) ) ENGINE = innodb;

# Questão 02
SELECT * FROM PRODUTO 
WHERE DATA BETWEEN '2020-01-01' AND '2021-02-09';

# Questão 03
SELECT * FROM PRODUTO WHERE 
NOT  DATA BETWEEN '2020-01-01' AND '2021-02-09';

# Questão 04
CREATE TABLE NOTAFISCAL (
NUMERO INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
VALOR DOUBLE(10,4), ID_PRODUTO INT, 
FOREIGN KEY fk_notasfiscais_idproduto (ID_PRODUTO) 
REFERENCES PRODUTO(ID))ENGINE = innodb;

# Questão 05
SELECT NUMERO FROM NOTAFISCAL WHERE ID_PRODUTO=455644;

# Questão 06
ALTER TABLE NOTAFISCAL CHANGE NUMERO ORDER_ID INT;

# Questão 07
UPDATE NOTAFISCAL SET ID_PRODUTO=243924 WHERE ID_PRODUTO=455644;

# Questão 08 Embora ja foi add na criação das tabelas
ALTER TABLE NOTAFISCAL ADD PRIMARY KEY(ID);

ALTER TABLE PRODUUTO ADD PRIMARY KEY(ID);

ALTER TABLE NOTAFISCAL
ADD CONSTRAINT fk_notasfiscais_idproduto
FOREIGN KEY (ID_PRODUTO)
REFERENCES produto (ID);